import { حالة } from '../main.js';import { الجولات } from '../data/rounds.js';import { HUD } from '../ui/HUD.js';import { CinematicSystem } from '../systems/CinematicSystem.js';import { صوت } from '../systems/AudioSystem.js';import { Player } from '../entities/Player.js';import { Enemy } from '../entities/Enemy.js';import { DialogueBox } from '../ui/DialogueBox.js';
export class ArenaScene extends Phaser.Scene{constructor(){super('ArenaScene');}
create(){this.a=صوت; this.a.resume(); this.a.موسيقى_القتال();this.hud=new HUD(this);this.drawArenaBackground();this.cameras.main.fadeIn(260,0,0,0);this.player=new Player(this,480,430,حالة);this.enemies=[];this.lastAttack='';this.repeat=0;this.stateTimer=0;this.blockTimer=0;this.bossBarBg=null;this.bossBar=null;this.bossTitle=null;this.paused=false;this.pauseUI=[];this.dashCd=0;this.attackCd=0;this.playerVx=0;this.playerVy=0;this.preBoss=false;
this.keys=this.input.keyboard.addKeys('W,A,S,D,LEFT,RIGHT,UP,DOWN,SPACE,Q,SHIFT,E,ESC');this.input.keyboard.on('keydown-ESC',()=>this.togglePause());this.spawn();}

showPreFinalDialogue(next){if(حالة.الجولة!==30||this.preBoss)return next();this.preBoss=true;const d=new DialogueBox(this);d.show([{متحدث:'العجوز',نص:'لقد بلغت الباب الأخير.'},{متحدث:'العجوز',نص:'ليس خلفه جيش، ولا وحش، ولا ملك.'},{متحدث:'العجوز',نص:'خلفه جوابٌ كنت تؤجله.'}],next,{speedMode:حالة.النمط==='نمط السرعة'});}

togglePause(){this.paused=!this.paused;if(this.paused){const dim=this.add.rectangle(480,270,960,540,0x000000,0.5).setDepth(90);const panel=this.add.rectangle(480,260,360,260,0x131b2b,0.95).setStrokeStyle(2,0x5a6d8d).setDepth(91);const mk=(y,t,cb)=>{const r=this.add.rectangle(480,y,260,42,0x1f2940).setInteractive({useHandCursor:true}).setDepth(92);const tx=this.add.text(480,y-12,t,{fontFamily:'Tahoma',fontSize:'22px',color:'#f1e7c7',rtl:true}).setOrigin(0.5,0).setDepth(93);r.on('pointerdown',cb);return [r,tx];};this.pauseUI=[dim,panel,...mk(200,'متابعة',()=>this.togglePause()),...mk(250,'إعادة المحاولة',()=>{this.paused=false;this.scene.restart();}),...mk(300,'العودة إلى القائمة',()=>{this.paused=false;this.scene.start('MainMenuScene');}),...mk(350,'الإعدادات',()=>{this.paused=false;this.scene.start('SettingsScene');})];}else{this.pauseUI.forEach(x=>x.destroy());this.pauseUI=[];}}

drawArenaBackground(){const w=960,h=540;this.add.rectangle(w/2,h/2,w,h,0x0a1020).setDepth(-20);for(let i=0;i<90;i++)this.add.rectangle(Phaser.Math.Between(0,w),Phaser.Math.Between(0,260),1,1,0xe0e8ff,Phaser.Math.FloatBetween(.25,.9)).setDepth(-19);this.add.circle(760,90,34,0xdadff1,0.82).setDepth(-19);this.add.circle(760,90,50,0xdadff1,0.15).setDepth(-19);this.add.rectangle(w/2,248,w,160,0x121a2d,0.8).setDepth(-18);this.add.rectangle(w/2,286,w,120,0x17233a,0.85).setDepth(-17);this.add.rectangle(w/2,220,90,130,0x1a2743,0.9).setStrokeStyle(2,0x7d95ce).setDepth(-16);this.add.rectangle(w/2,230,40,70,0x0f1628,0.95).setDepth(-15);for(let i=0;i<14;i++){const fog=this.add.ellipse(Phaser.Math.Between(80,880),Phaser.Math.Between(270,430),Phaser.Math.Between(120,220),Phaser.Math.Between(28,42),0xc8d6ff,0.06).setDepth(-14);this.tweens.add({targets:fog,x:fog.x+Phaser.Math.Between(-20,20),alpha:{from:0.03,to:0.08},duration:Phaser.Math.Between(2200,4200),yoyo:true,repeat:-1});}for(let i=0;i<24;i++){const p=this.add.rectangle(Phaser.Math.Between(0,w),Phaser.Math.Between(250,500),2,2,0xdce7ff,0.35).setDepth(-13);this.tweens.add({targets:p,y:p.y-Phaser.Math.Between(10,26),alpha:0,duration:Phaser.Math.Between(1400,2600),repeat:-1,delay:Phaser.Math.Between(0,1400)});}this.add.rectangle(w/2,494,w,92,0x2a2e3a).setDepth(-12);for(let x=0;x<w;x+=16)this.add.rectangle(x+8,466,16,6,(x/16)%2?0x363c4c:0x2f3443).setDepth(-11);}

spawn(){const r=الجولات[حالة.الجولة-1];this.enemies.forEach(e=>e.container?.destroy());this.enemies=[];if(this.bossBarBg){this.bossBarBg.destroy();this.bossBar.destroy();this.bossTitle.destroy();this.bossBarBg=this.bossBar=this.bossTitle=null;}const c=r.زعيم?1:Math.max(2,Math.floor(r.اعداء*(1+حالة.الجولة*0.015)));const run=()=>{if(r.زعيم){const dim=this.add.rectangle(480,270,960,540,0x000000,0.65);this.tweens.add({targets:dim,alpha:0,duration:480,onComplete:()=>dim.destroy()});this.a.دخول_بوس();this.a.موسيقى_البوس();CinematicSystem.shake(this);this.bossTitle=this.add.text(480,122,`مواجهة: ${r.زعيم}`,{fontFamily:'Tahoma',fontSize:'28px',color:'#ffd8de',rtl:true}).setOrigin(0.5,0.5);this.tweens.add({targets:this.bossTitle,alpha:{from:0,to:1},duration:220,yoyo:true,hold:700,onComplete:()=>this.bossTitle.setAlpha(0.8)});}for(let i=0;i<c;i++){const x=i%2?60:900;const y=140+Math.random()*240;const e=new Enemy(this,x,y,r.زعيم?'boss':'normal',r.زعيم||'');e.speed*=1+Math.min(0.45,حالة.الجولة*0.01);this.enemies.push(e);}if(r.زعيم){this.bossBarBg=this.add.rectangle(480,104,360,14,0x2b2f3f).setDepth(41);this.bossBar=this.add.rectangle(302,104,352,8,0xc44556).setOrigin(0,0.5).setDepth(42);}if(r.زعيم==='الذات الأخيرة'){const pulse=this.add.rectangle(480,270,960,540,0x5b2a46,0.04).setDepth(10);this.tweens.add({targets:pulse,alpha:{from:0.02,to:0.09},duration:520,yoyo:true,repeat:12,onComplete:()=>pulse.destroy()});}};
if(r.زعيم&&r.رقم===30)this.showPreFinalDialogue(run); else run();}

visualSlash(){const s=this.add.rectangle(this.player.x+this.player.dir*26,430,30,8,0xe9f0ff,0.85);this.tweens.add({targets:s,alpha:0,width:46,duration:120,onComplete:()=>s.destroy()});}
visualArrow(){const a=this.add.rectangle(this.player.x+this.player.dir*14,426,10,2,0xcba56d);const trail=[];for(let i=0;i<3;i++){const t=this.add.rectangle(a.x-i*3*this.player.dir,426,2,2,0xe7cda0,0.7);trail.push(t);}this.tweens.add({targets:a,x:a.x+this.player.dir*90,duration:150,onUpdate:()=>{trail.forEach((t,i)=>{t.x=a.x-(i+1)*4*this.player.dir;t.alpha=Math.max(0,0.8-i*0.2);});},onComplete:()=>{a.destroy();trail.forEach(t=>t.destroy());}});}
visualCrit(x,y){const f=this.add.circle(x,y,10,0xfff2a8,0.9);this.tweens.add({targets:f,alpha:0,scale:2,duration:130,onComplete:()=>f.destroy()});}
visualShield(){const sh=this.add.circle(this.player.x+this.player.dir*12,430,16,0x98b1d8,0.25).setStrokeStyle(2,0xd8e5ff);this.tweens.add({targets:sh,alpha:0,duration:180,onComplete:()=>sh.destroy()});}

pickTargetInRange(range){const inR=this.enemies.filter(e=>e.alive&&Math.abs(e.container.x-this.player.x)<=range);if(!inR.length)return null;return inR[Math.floor(Math.random()*inR.length)];}

attack(kind='basic'){if(!this.enemies.length||this.attackCd>0)return;this.attackCd=kind==='basic'?170:240; if(this.lastAttack===kind)this.repeat++; else this.repeat=0; this.lastAttack=kind;
const range=kind==='secondary'?140:(حالة.الكلاس==='vanguard'?44:36); const target=this.pickTargetInRange(range); if(!target)return;
let dmg=1; if(حالة.الكلاس==='hunter'&&Math.random()<0.22){dmg=2; this.visualCrit(target.container.x,target.container.y);} if(kind==='basic'&&حالة.الكلاس==='ronin')this.visualSlash(); if(kind==='secondary'&&(حالة.الكلاس==='ronin'||حالة.الكلاس==='hunter'))this.visualArrow();
if(حالة.الجولة===30&&Math.random()<0.2){target.container.x+=Math.random()<0.5?-40:40;return;} if(حالة.الجولة===30&&this.repeat>2&&Math.random()<0.6){let pdmg=5; if(حالة.الكلاس==='vanguard'&&this.blockTimer>0)pdmg=2; حالة.الصحة-=pdmg;this.player.setState('تضرر');this.stateTimer=180;CinematicSystem.shake(this);} this.player.setState('هجوم');this.stateTimer=120;
if(target.kind==='boss'&&target.bossName==='الذات الأخيرة'&&this.repeat>1&&Math.random()<0.45){حالة.الصحة-=3;}
// knockback on enemy
const kb=(حالة.الكلاس==='vanguard'?22:16)*this.player.dir; target.container.x+=kb;
if(target.kind==='boss'){if(target.hp<=(target.maxHp/2)&&target.bossName==='الذات الأخيرة')target.speed=1.9;}
target.takeHit(dmg); if(!target.alive){this.enemies=this.enemies.filter(e=>e!==target);حالة.القتلى++;if(Math.random()<0.06)حالة.السهام=Math.min(12,حالة.السهام+1);this.a.موت();}
if(this.bossBar&&target.kind==='boss'){this.bossBar.width=352*Math.max(0,target.hp/target.maxHp);for(let i=0;i<5;i++){const bp=this.add.rectangle(target.container.x+Math.random()*12-6,target.container.y+Math.random()*12-6,2,2,0xff8ea8,0.9);this.tweens.add({targets:bp,alpha:0,y:bp.y-10,duration:150,onComplete:()=>bp.destroy()});}} this.a.إصابة();
if(this.enemies.length===0){this.a.نهاية_جولة(); if(حالة.الجولة===30){this.scene.start('EndingScene');return;} حالة.الجولة++; if(حالة.الجولة%5===1)this.scene.start('RestGateScene'); else {this.a.موسيقى_القتال();this.spawn();}}}

update(_,dt){if(this.paused)return;const base=حالة.الكلاس==='hunter'?0.55:حالة.الكلاس==='vanguard'?0.34:0.42;const max=حالة.الكلاس==='hunter'?4.4:حالة.الكلاس==='vanguard'?2.8:3.5;
let ax=0;if(this.keys.LEFT.isDown||this.keys.A.isDown){ax=-base;this.player.dir=-1;} if(this.keys.RIGHT.isDown||this.keys.D.isDown){ax=base;this.player.dir=1;}
this.playerVx=Phaser.Math.Clamp(this.playerVx+ax,-max,max); if(ax===0)this.playerVx*=0.82; this.player.x+=this.playerVx;
let moving=Math.abs(this.playerVx)>0.2;
if(Phaser.Input.Keyboard.JustDown(this.keys.SPACE)) {this.a.ضربة_سيف();if(Math.random()<0.18)CinematicSystem.shake(this);this.attack('basic');}
if(Phaser.Input.Keyboard.JustDown(this.keys.Q)&&حالة.السهام>0){حالة.السهام--;this.a.سهم();this.attack('secondary');}
if(this.dashCd>0)this.dashCd-=dt;
if(Phaser.Input.Keyboard.JustDown(this.keys.SHIFT)&&this.dashCd<=0){this.dashCd=900;for(let i=0;i<6;i++){const dust=this.add.rectangle(this.player.x-Math.random()*20*this.player.dir,438,2,2,0xbdc8df,0.6);this.tweens.add({targets:dust,alpha:0,y:dust.y-Phaser.Math.Between(6,14),x:dust.x-Phaser.Math.Between(4,10)*this.player.dir,duration:180,onComplete:()=>dust.destroy()});}if(حالة.الكلاس==='hunter'){this.playerVx+=this.player.dir*3.2;this.player.setState('اندفاع');this.stateTimer=180;} else if(حالة.الكلاس==='vanguard'){this.blockTimer=350;this.player.setState('صد');this.stateTimer=160;this.visualShield();} else {this.playerVx+=this.player.dir*2.2;this.player.setState('اندفاع');this.stateTimer=120;} this.a.اندفاع();}
if(Phaser.Input.Keyboard.JustDown(this.keys.E)&&حالة.الكلاس==='vanguard'){this.a.ضربة_ثقيلة();this.attack('counter'); this.player.setState('هجوم'); this.stateTimer=140;}
if(this.blockTimer>0)this.blockTimer-=dt; if(this.attackCd>0)this.attackCd-=dt;
if(this.stateTimer>0){this.stateTimer-=dt;}else{this.player.setState(moving?'مشي':'وقوف');}
this.player.update(dt);
this.enemies.forEach(e=>{e.update(dt,this.player.x);const d=Math.abs(e.container.x-this.player.x); if(d<18){const push=(18-d)*0.08; e.container.x+=e.container.x>this.player.x?push:-push;} if(e.alive&&d<24&&Math.random()<0.008){let dmg=e.kind==='boss'?3:1; if(حالة.الكلاس==='vanguard'&&this.blockTimer>0)dmg=1; حالة.الصحة-=dmg; this.player.setState('تضرر'); this.stateTimer=120; this.playerVx += (e.container.x>this.player.x?-1:1)*1.8; }});
if(حالة.النمط==='نمط السرعة')حالة.الوقت+=dt/1000; if(حالة.الصحة<=0){حالة.السقوط++; this.scene.start('GameOverScene'); return;} this.hud.update(حالة);} }
